import 'package:flutter_app/core/common/cubits/app_user/app_user_cubit.dart';
import 'package:flutter_app/core/network/connection_checker.dart';
import 'package:flutter_app/core/secrets/app_secrets.dart';
import 'package:flutter_app/features/auth/data/datasources/auth_remote_data_source.dart';
import 'package:flutter_app/features/auth/data/repositories/auth_repository_impl.dart';
import 'package:flutter_app/features/auth/domain/repositories/auth_repository.dart';
import 'package:flutter_app/features/auth/domain/usecases/current_user.dart';
import 'package:flutter_app/features/auth/domain/usecases/user_login.dart';
import 'package:flutter_app/features/auth/domain/usecases/user_sign_up.dart';
import 'package:flutter_app/features/auth/presentation/bloc/auth_bloc.dart';
import 'package:flutter_app/features/song/data/datasources/song_local_data_source.dart';
import 'package:flutter_app/features/song/data/datasources/song_remote_data_source.dart';
import 'package:flutter_app/features/song/data/repositories/song_repository_impl.dart';
import 'package:flutter_app/features/song/domain/repositories/song_repository.dart';
import 'package:flutter_app/features/song/domain/usecases/get_all_songs.dart';
import 'package:flutter_app/features/song/domain/usecases/get_liked_song.dart';
import 'package:flutter_app/features/song/domain/usecases/upload_song.dart';
// import 'package:flutter_app/features/player/presentation/bloc/player_bloc.dart';
import 'package:flutter_app/features/song/presentation/bloc/song_bloc.dart';
import 'package:get_it/get_it.dart';
import 'package:hive/hive.dart';
import 'package:internet_connection_checker_plus/internet_connection_checker_plus.dart';
import 'package:path_provider/path_provider.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

part 'init_dependencies.main.dart';